"""Condition expression AST for deterministic transition evaluation.

Conditions are structured JSON expressions that:
- Can be generated by an LLM (structured output)
- Can be evaluated deterministically at runtime
- Are fully serializable via Pydantic
"""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, Field


class Operator(str, Enum):
    """Comparison operators for field conditions."""

    EQ = "eq"
    NE = "ne"
    GT = "gt"
    LT = "lt"
    GTE = "gte"
    LTE = "lte"
    IN = "in"
    NOT_IN = "not_in"
    CONTAINS = "contains"
    MATCHES = "matches"


class LogicOperator(str, Enum):
    """Logical operators for compound conditions."""

    AND = "and"
    OR = "or"
    NOT = "not"


class FieldCondition(BaseModel):
    """Leaf condition: compare a field in the observation against a value.

    The field supports dot-path notation for nested access,
    e.g. "user.intent" accesses observation["user"]["intent"].
    """

    type: Literal["field"] = "field"
    field: str
    operator: Operator
    value: Any

    model_config = {"frozen": True}


class ConditionGroup(BaseModel):
    """Compound condition combining multiple sub-conditions with a logical operator.

    For NOT, the conditions list should contain exactly one element.
    """

    type: Literal["group"] = "group"
    logic: LogicOperator
    conditions: list[Annotated[Union["FieldCondition", "ConditionGroup", "AlwaysTrue"], Field(discriminator="type")]]

    model_config = {"frozen": True}


class AlwaysTrue(BaseModel):
    """Sentinel condition that always evaluates to true.

    Used for default/wildcard transitions — the fallback when no other
    condition matches.
    """

    type: Literal["always_true"] = "always_true"

    model_config = {"frozen": True}


# Union type for any condition expression
ConditionExpr = Annotated[
    Union[FieldCondition, ConditionGroup, AlwaysTrue],
    Field(discriminator="type"),
]
